### ISSUE TITLE
CexControl doesn't work since commit 03662ad ("Change Logging")

### ISSUE THREAD

**Issue by stevenh512** [Eloque/CexControl#1] opened 2013-12-15 08:07 UTC
Every commit since 03662ad gives me the following error (copied from CexControl.log):

```
1387093886 Start cycle at Sat Dec 14 23:51:26 2013
1387093895 GHS balance: 1.7076357
1387093895 
1387093898 1 NMC is 0.09015089 GHS
1387093898 1 NMC is 0.00663780 BTC
1387093898 1 BTC is 13.62873155 GHS
1387093898 1 BTC is 150.65232457 NMC
1387093898 
1387093898 Unexpected error:
1387093898 <type 'exceptions.TypeError'>
1387093898 An error occurred, skipping cycle
```

I get this error on my own machine running either Ubuntu 12.10 64-bit or Ubuntu 13.10 32-bit (I've tried it with both) and also on a VPS (where I normally run the bot) running Ubuntu 12.10 Server 64-bit.

When I revert to commit 12958f98 everything works fine using the same configuration file. I'm not much of a Python expert but I don't see what changes in 03662ad would be causing this problem, otherwise this would be a pull request. :)

If it helps, I can post my configuration file with the API key and secret removed, but the config was created by CexControl.py and works fine with 12958f98 and older commits. For now I'll just keep running the older version since it works for me, but hopefully this is an easy fix so I can keep up to date with any new changes.

**Comment by billchilders** [comment] 2013-12-16 04:32
I'm seeing the exact same issue. I've even nuked my config and generated a new one with the "newconfig" directive -- no dice, it still happens.

**Comment by Eloque** [comment] 2013-12-16 08:29
I think I spotted the error, thing is, I can't reproduce it on any of my machines. I will however update the settings bit to use 0 and 1 integers instead of strings. It was kinda late when I made a commit for that.

**Comment by Eloque** [comment] 2013-12-16 12:55
Logging broke indeed, it is now fixed in the lastest version.

**Closed as completed by Eloque** 2013-12-16 12:55 UTC
Labels: bug

**Comment by codydh** [comment] 2013-12-16 13:01
Just pulled the repository clean and started from scratch, and here's what I'm seeing:

```
Start cycle at Mon Dec 16 13:00:19 2013
GHS balance: 1.61996569

1 NMC is 0.08772178 GHS
1 NMC is 0.00635560 BTC
1 BTC is 13.81368107 GHS
1 BTC is 157.34155705 NMC

1 BTC via NMC is 13.80228131 GHS
Efficiency : 99.92
1 NMC via BTC is 0.08779423 GHS
Efficiency : 100.08

Buy BTC then use that to buy GHS
Target Coin set to: BTC

Efficiency threshold: 2.5
Efficiency possible: 0.08
Arbitration not desired, hold non target coins this cycle
BTC Balance: 0.00059200
NMC Balance: 0.00128005
----------------------------------------
Unexpected error:
<type 'exceptions.TypeError'>
An error occurred, skipping cycle

Cycle completed, idle for 150 seconds
```

**Comment by Eloque** [comment] 2013-12-16 13:03
Different error. Will check.

**Comment by codydh** [comment] 2013-12-16 13:04
Ah ok, apologies, added it to this one because it looked the same to me.

**Comment by Eloque** [comment] 2013-12-16 13:06
Actually, you were right. Same cause, different error, same result. 
The print function was replaced by a generic log function. It should be fixed now.

**Comment by aaronrudolph** [comment] 2013-12-28 07:35
I get the following error:

Attempting to load Settings
File found, loaded

Configuration created, attempting save

# Save successfull, attempting reload

Account       : dakine259
== !! ============================ !! ==
Error:
Permission denied

Could not connect Cex.IO, exiting
== !! ============================ !! ==

**Comment by GuyPaddock** [comment] 2014-10-31 15:06
Make sure that the API key created on CEX has all the right permissions (check balance, make and cancel trades, etc).
